### ISSUE TITLE
exception when making parameters final

### ISSUE THREAD

**Issue by champgm** [champgm/IntelliJCodeGenerationPlugin#33]
Happened in VenueAggregator:

com.intellij.psi.impl.source.javadoc.PsiDocMethodOrFieldRef cannot be cast to com.intellij.psi.PsiReferenceExpression
java.lang.ClassCastException: com.intellij.psi.impl.source.javadoc.PsiDocMethodOrFieldRef cannot be cast to com.intellij.psi.PsiReferenceExpression
	at com.champgm.intellij.plugin.PluginUtil.isModified(PluginUtil.java:63)
	at com.champgm.intellij.plugin.finalize.MakeFieldsFinal.doAction(MakeFieldsFinal.java:48)
	at com.champgm.intellij.plugin.Maction$1.run(Maction.java:22)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:166)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
	at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
	at com.champgm.intellij.plugin.Maction.actionPerformed(Maction.java:19)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$7.run(ActionManagerImpl.java:1420)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:651)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:632)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:602)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:498)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2108)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:476)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:59)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecuteNow(ActionManagerImpl.java:1376)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$300(ActionManagerImpl.java:75)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$6.run(ActionManagerImpl.java:1359)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by champgm** [comment]
fixed in #34
