### ISSUE TITLE
Something attempting to modify already-compiled source

### ISSUE THREAD

**Issue by champgm** [champgm/IntelliJCodeGenerationPlugin#40]
I think this is only happening in AndroidStudio, but it's still annoying. I am almost certain that this is caused by field finalization attempting to finalize the fields in superclasses when those classes are already compiled resources.... or something.
```
Cannot modify compiled element: Cannot modify compiled element
com.intellij.util.IncorrectOperationException: Cannot modify compiled element
	at com.intellij.psi.impl.compiled.ClsModifierListImpl.setModifierProperty(ClsModifierListImpl.java:54)
	at com.champgm.intellij.plugin.finalize.MakeFieldsFinal.doAction(MakeFieldsFinal.java:56)
	at com.champgm.intellij.plugin.Maction$1.run(Maction.java:22)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:168)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
	at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:118)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:115)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:112)
	at com.intellij.openapi.command.WriteCommandAction.access$000(WriteCommandAction.java:33)
	at com.intellij.openapi.command.WriteCommandAction$1.run(WriteCommandAction.java:80)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:85)
	at com.champgm.intellij.plugin.Maction.actionPerformed(Maction.java:19)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$7.run(ActionManagerImpl.java:1460)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:651)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:632)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:602)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:498)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2057)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:476)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:59)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecuteNow(ActionManagerImpl.java:1416)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$600(ActionManagerImpl.java:73)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$6.run(ActionManagerImpl.java:1399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by champgm** [comment]
fix in #41
